### ISSUE TITLE
Bootstrap Store, Redux, and Logics

### ISSUE THREAD

**Issue by pdvorchik** [townhallproject/admin#16]
**User Story**
An admin wants to be able to fetch and store information on the events, mocs, and users,

**Notes**
Started doing this as part of the homepage, but it was getting large enough I broke it out into it's own issue.

**Tasks**
- [x] Install all deps
- [x] Add states for Events, MoCs, and Users
- [x] Add logics to handle ajax requests
- [x] Add the store to the root app
